In [21]:
import pandas

In [56]:
dataset = pandas.read_csv('data/owid-covid-data.csv')

In [23]:
dataset.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,BRA,South America,Brazil,2020-02-26,1.0,1.0,NaN,NaN,NaN,NaN,...,10.1,17.9,NaN,2.2,75.88,0.765,NaN,NaN,NaN,NaN
1,BRA,South America,Brazil,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,10.1,17.9,NaN,2.2,75.88,0.765,NaN,NaN,NaN,NaN
2,BRA,South America,Brazil,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,10.1,17.9,NaN,2.2,75.88,0.765,NaN,NaN,NaN,NaN
3,BRA,South America,Brazil,2020-02-29,2.0,1.0,NaN,NaN,NaN,NaN,...,10.1,17.9,NaN,2.2,75.88,0.765,7049.6,3.31,5.25,32.943066
4,BRA,South America,Brazil,2020-03-01,2.0,0.0,NaN,NaN,NaN,NaN,...,10.1,17.9,NaN,2.2,75.88,0.765,NaN,NaN,NaN,NaN

### Questão 1
Qual é o total exato de linhas e colunas presentes neste conjunto de dados, considerando que precisamos mapear o tamanho do nosso arquivo de trabalho?

In [24]:
dataset.shape

(7663, 67)

### Questão 2
Quais são os continentes catalogados neste conjunto de dados, imaginando que estamos planejando uma expedição global de saúde e precisamos dos destinos únicos?

In [25]:
dataset[['continent']]

          continent
0     South America
1     South America
2     South America
3     South America
4     South America
...             ...
7658  North America
7659  North America
7660  North America
7661  North America
7662  North America

[7663 rows x 1 columns]

### Questão 3
Qual é a quantidade exata de registros diários que cada país enviou para este conjunto de dados, de modo a descobrirmos as nações mais assíduas na documentação?

In [26]:
dataset[['new_cases', 'location']].groupby('location').agg('sum')

                 new_cases
location
Brazil          28935718.0
France          23488526.0
Germany         15831207.0
India           42962953.0
Italy           12990371.0
Japan            5341244.0
Russia          16619507.0
South Korea      4456263.0
United Kingdom  18331636.0
United States   79265725.0

### Questão 4
Quais são os principais indicadores estatísticos descritivos, como a média, o mínimo, o máximo e os quartis, para o índice de rigorosidade das restrições presentes neste conjunto de dados, assumindo que um sociólogo pediu um resumo das medidas de confinamento?

In [27]:
dataset.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,7.663000e+03,7.641000e+03,7484.000000,7345.000000,7327.000000,7173.000000,7663.000000,7641.000000,7484.000000,7345.000000,...,7663.000000,7663.000000,7.660000e+02,7663.000000,7663.000000,7663.000000,6.920000e+02,692.000000,692.000000,692.000000
mean,7.413453e+06,3.248569e+04,32590.349244,143683.851464,420.451071,423.776663,40129.002883,218.335670,215.706487,849.127797,...,17.022224,31.774449,5.955000e+01,5.882298,79.370521,0.867278,1.277382e+05,7.168382,10.014639,868.361431
std,1.200763e+07,6.990790e+04,66130.926542,193260.956591,656.855964,611.463015,53182.233431,514.898513,475.288902,856.364728,...,8.869313,11.113599,1.422014e-14,4.150498,4.790136,0.090695,2.181352e+05,7.737350,16.272627,1006.519309
min,1.000000e+00,0.000000e+00,0.000000,1.000000,0.000000,0.000000,0.001000,0.000000,0.000000,0.001000,...,1.900000,17.900000,5.955000e+01,0.530000,69.660000,0.645000,-3.772610e+04,-9.020000,-19.200000,-299.292834
25%,2.297820e+05,1.333000e+03,1440.107250,10145.000000,23.000000,27.857000,2831.535000,12.022000,12.578000,98.069000,...,10.100000,24.600000,5.955000e+01,2.540000,75.880000,0.824000,-1.335500e+02,-0.052500,-0.252500,-2.603051
50%,2.702681e+06,9.921000e+03,11149.928500,83976.000000,161.000000,177.714000,17491.567000,62.362000,67.154500,554.520000,...,19.800000,33.100000,5.955000e+01,5.980000,81.330000,0.916000,5.249990e+04,6.900000,5.745000,707.315534
75%,7.906961e+06,3.357100e+04,35266.357250,149512.000000,535.500000,567.143000,64999.770000,209.744000,216.940500,1631.352000,...,23.400000,35.600000,5.955000e+01,8.050000,83.030000,0.926000,1.191370e+05,13.530000,14.987500,1517.147097
max,7.926573e+07,1.368167e+06,802518.429000,958437.000000,4529.000000,4190.000000,342095.547000,7453.161000,5436.723000,3047.832000,...,30.100000,58.300000,5.955000e+01,13.050000,84.630000,0.947000,1.080748e+06,30.850000,107.250000,7406.847532

### Questão 5
Quais seriam dez linhas extraídas de forma totalmente aleatória deste conjunto de dados, após o gerente do projeto pedir uma auditoria rápida e surpresa nos testes diários?

In [36]:
dataset.sample(10)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
3660,ITA,Europe,Italy,2021-10-06,4689341.0,3232.0,3011.429,131157.0,39.0,41.000,...,19.8,27.8,NaN,3.18,83.51,0.892,NaN,NaN,NaN,NaN
4358,JPN,Asia,Japan,2021-07-22,857725.0,5399.0,3836.429,15107.0,6.0,12.571,...,11.2,33.7,NaN,13.05,84.63,0.919,NaN,NaN,NaN,NaN
6258,GBR,Europe,United Kingdom,2020-06-13,271158.0,887.0,1011.857,39385.0,107.0,110.571,...,20.0,24.7,NaN,2.54,81.32,0.932,NaN,NaN,NaN,NaN
3752,ITA,Europe,Italy,2022-01-06,6975465.0,219430.0,142005.286,138474.0,198.0,175.286,...,19.8,27.8,NaN,3.18,83.51,0.892,NaN,NaN,NaN,NaN
7046,USA,North America,United States,2020-06-27,2511531.0,41268.0,37152.714,126116.0,496.0,551.286,...,19.1,24.6,NaN,2.77,78.86,0.926,NaN,NaN,NaN,NaN
1353,FRA,Europe,France,2021-09-29,7052733.0,5900.0,5257.143,116666.0,43.0,49.571,...,30.1,35.6,NaN,5.98,82.66,0.901,NaN,NaN,NaN,NaN
1099,FRA,Europe,France,2021-01-18,2955071.0,3736.0,18261.286,70698.0,403.0,375.143,...,30.1,35.6,NaN,5.98,82.66,0.901,NaN,NaN,NaN,NaN
2685,IND,Asia,India,2021-03-10,11285561.0,22854.0,18376.857,158189.0,126.0,107.714,...,1.9,20.6,59.55,0.53,69.66,0.645,NaN,NaN,NaN,NaN
893,FRA,Europe,France,2020-06-26,203034.0,1263.0,512.571,29780.0,26.0,22.857,...,30.1,35.6,NaN,5.98,82.66,0.901,NaN,NaN,NaN,NaN
2571,IND,Asia,India,2020-11-16,8874290.0,29163.0,40365.714,130519.0,449.0,494.286,...,1.9,20.6,59.55,0.53,69.66,0.645,NaN,NaN,NaN,NaN

### Questão 6
Qual é o valor do produto interno bruto per capita posicionado exatamente na centésima linha deste conjunto de dados, sabendo que um algoritmo detectou uma anomalia nessa posição específica?

In [38]:
dataset['gdp_per_capita'].iloc[99] # 0 < 99

np.float64(14103.452)

### Questão 7
Qual é o país que possui a maior expectativa de vida registrada, focando o nosso estudo demográfico apenas nos registros europeus deste conjunto de dados?

In [45]:
dataset[dataset['continent'] == 'Europe'].sort_values('life_expectancy', ascending=False).head(1)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
3047,ITA,Europe,Italy,2020-02-01,2.0,0.0,NaN,NaN,NaN,NaN,...,19.8,27.8,NaN,3.18,83.51,0.892,NaN,NaN,NaN,NaN

### Questão 8
Qual é a média global de uma nova coluna chamada `cases_per_thousand`, criada através da divisão do total de casos pela população e multiplicada por mil, assumindo que você deve remover definitivamente a coluna original de total de casos deste conjunto de dados para normalizar as métricas de contágio?

In [57]:
dataset['cases_per_thousand'] = (dataset['total_cases'] / dataset['population']) * 1000
dataset = dataset.drop(columns = ['total_cases'])
dataset['cases_per_thousand'].mean()

np.float64(40.129002883081895)

### Questão 9
Qual é a quantidade exata de registros associada a cada um dos continentes neste conjunto de dados, para que possamos planejar a capacidade dos nossos servidores?

In [ ]:
dataset.groupby('continent').size()

continent
Asia             2314
Europe           3836
North America     774
South America     739
dtype: int64

### Questão 10
Quais são os valores da mediana de idades para os dez dias com os piores números absolutos de novos casos globais neste conjunto de dados, com o intuito de analisar o perfil demográfico das fases mais agudas da pandemia?

In [ ]:
dataset.sort_values('new_cases', ascending=False).iloc[ : 10].loc[: , 'median_age']
# ascending=False -> decrescente

7608    38.3
7616    38.3
7601    38.3
7617    38.3
7610    38.3
7622    38.3
7612    38.3
7605    38.3
7611    38.3
7619    38.3
Name: median_age, dtype: float64

### Questão 11
Qual é a data exata que apresentou a maior proporção de casos críticos neste conjunto de dados, exigindo que você crie uma nova coluna chamada `critical_ratio` resultante da divisão dos pacientes em unidades de terapia intensiva pelo total de pacientes hospitalizados, descartando a coluna original de pacientes hospitalizados logo em seguida para avaliar a sobrecarga aguda do sistema de saúde?

In [67]:
dataset['critical_ratio'] = dataset['icu_patients'] / dataset['hosp_patients']
dataset.drop(columns = ['hosp_patients'])
dataset.sort_values('critical_ratio', ascending=False)['date'].iloc[0]

'2021-10-27'

### Questão 12
Quais são os países que mantiveram uma média diária de novos casos superior a dez mil ao longo de todo o seu histórico registrado neste conjunto de dados, para que possamos identificar os surtos mais descontrolados?

In [ ]:
dataset.groupby('location').filter(lambda row : row['new_cases'].mean() > 10000)['location'].unique()
# groupby('location') -> agrupa por localização
# filter(lambda row : row['new_cases'].mean() > 10000) -> filtra os grupos onde a média de new_cases é maior que 10000
# ['location'].unique() -> retorna as localizações únicas dos grupos filtrados

<StringArray>
[        'Brazil',         'France',        'Germany',          'India',
          'Italy',         'Russia', 'United Kingdom',  'United States']
Length: 8, dtype: str

### Questão 13
Quais países registraram um desvio padrão superior a mil unidades na métrica de pacientes internados em unidades de terapia intensiva considerando todo o período documentado neste conjunto de dados, de forma a mapear o caos hospitalar?

In [72]:
dataset.groupby('location').filter(lambda row : row['icu_patients'].std() > 1000)['location'].unique()

<StringArray>
['France', 'Germany', 'Italy', 'United States']
Length: 4, dtype: str

### Questão 14
Qual é o maior valor de prevalência de diabetes registrado apenas para os países onde a taxa de mortalidade ultrapassou dois por cento da população neste conjunto de dados, exigindo a criação prévia de uma coluna chamada `death_population_ratio` resultante do total acumulado de mortes dividido pela população para analisar fatores de risco em cenários extremos?

In [75]:
dataset['death_population_ratio'] = dataset['total_deaths'] / dataset['population']
dataset.groupby('location').filter(lambda row : row['death_population_ratio'].max() > 0.02)['diabetes_prevalence'].max()

nan

### Questão 15
Quais países conseguiram manter uma mediana diária de novos testes superior a cinco mil ao longo de toda a sua trajetória neste conjunto de dados, de forma a podermos premiar as nações com rastreamento populacional constante?

In [76]:
dataset.groupby('location').filter(lambda row : row['new_tests'].median() > 5000)['location'].unique()

<StringArray>
[        'Brazil',         'France',          'India',          'Italy',
          'Japan',         'Russia',    'South Korea', 'United Kingdom',
  'United States']
Length: 9, dtype: str